export const assets = {
  logo: '/assets/brand/logo.svg',
  hero: '/assets/banners/hero.png',
  partner: '/assets/banners/partner.png',
  chevron: '/assets/navigation/carousel-chevron.svg',
  categories: {
    tecnologia: '/assets/categories/technology.png',
    supermercado: '/assets/categories/supermarket.png',
    bebidas: '/assets/categories/drinks.png',
    ferramentas: '/assets/categories/tools.png',
    saude: '/assets/categories/health.png',
    esportes: '/assets/categories/sports.png',
    moda: '/assets/categories/fashion.png',
  },
  shield: '/assets/header/shield.svg',
  truck: '/assets/header/truck.svg',
  creditCard: '/assets/header/credit-card.svg',
  orders: '/assets/header/orders.svg',
  heart: '/assets/header/heart.svg',
  user: '/assets/header/user.svg',
  cart: '/assets/header/cart.svg',
  crown: '/assets/header/crown.svg',
  search: '/assets/header/search.svg',
  modal: {
    closeA: '/assets/modal/close-a.svg',
    closeB: '/assets/modal/close-b.svg',
    plus: '/assets/modal/plus.svg',
    minus: '/assets/modal/minus.svg',
  },
  instagram: '/assets/footer/instagram.svg',
  facebook: '/assets/footer/facebook.svg',
  linkedin: '/assets/footer/linkedin.svg',
} as const;
